apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
      - name: transfer-service-container
        image: onedatashare/transfer_service:v1
        imagePullPolicy: Never
        envFrom:
        # For the below secrets make sure to execute command:
        # kubectl create secret generic ts-secrets-dev --from-env-file=jacob.env
        # I have the YAML for this but it's not secured as secrets are just base64 encoded.
        - secretRef:
            name: ts-secrets-dev
        ports:
        - containerPort: 8092
