FROM maven:3.6.3-jdk-11 AS build

COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package -DskipTests

FROM alpine:3.16.2 as pmeter-build
RUN apk add --update --no-cache git build-base python3 linux-headers python3-dev && \ 
    ln -sf python3 /usr/bin/python && python -m ensurepip \
    && pip3 install --upgrade pip setuptools \
    && rm -r /usr/lib/python*/ensurepip && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    rm -r /root/.cache

RUN git clone https://github.com/didclab/pmeter.git && cd pmeter && \
    pip install --user .


ARG ALPINE_VERSION=3.16

FROM python:3.10.5-alpine${ALPINE_VERSION} as aws-build

# Latest version
ARG AWS_CLI_VERSION=2.7.27
RUN apk add --no-cache git unzip groff build-base libffi-dev cmake
RUN git clone --single-branch --depth 1 -b ${AWS_CLI_VERSION} https://github.com/aws/aws-cli.git

WORKDIR aws-cli
RUN sed -i'' 's/PyInstaller.*/PyInstaller==5.2/g' requirements-build.txt
RUN python -m venv venv
RUN . venv/bin/activate
RUN scripts/installers/make-exe
RUN unzip -q dist/awscli-exe.zip
RUN aws/install --bin-dir /aws-cli-bin
RUN /aws-cli-bin/aws --version

RUN rm -rf /usr/local/aws-cli/v2/current/dist/aws_completer /usr/local/aws-cli/v2/current/dist/awscli/data/ac.index /usr/local/aws-cli/v2/current/dist/awscli/examples
RUN find /usr/local/aws-cli/v2/current/dist/awscli/botocore/data -name examples-1.json -delete


# Final Image
FROM alpine:3.16.2
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python && \
    apk add --no-cache openjdk11 --repository=https://dl-cdn.alpinelinux.org/alpine/latest-stable/community && \
    apk add --no-cache aws-cli

COPY --from=build /home/app/target/ods-transfer-service-0.0.1-SNAPSHOT.jar /usr/local/lib/ods-transfer-service-0.0.1-SNAPSHOT.jar

COPY --from=pmeter-build  /root/.local /root/.local
RUN export PATH=/root/.local/bin:$PATH && \
    mkdir -p /app/scripts /app/config /app/certs
COPY --from=aws-build /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=aws-build /aws-cli-bin/ /usr/local/bin/
ADD scripts/runner.sh /app/scripts/runner.sh
RUN chmod u+x /app/scripts/runner.sh
EXPOSE 8083
ENTRYPOINT ["/bin/sh","-c","/app/scripts/runner.sh"]